### ISSUE TITLE
GUI flexibly handling times in TimeSeries

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#12]
Let's think about how best to handle times in TimeSeries objects. If the data is supplied with a rate, then obviously we should use it, and the GUI should reflect that this is our only option. If the input data supplies timestamps instead of rate, I think it would be nice for all `TimeSeries` objects to have 3 options:

* [ ] use timestamps
* [ ] calculate rate and starting_time
* [ ] auto

Where `auto` is selected by default and it tests if the max difference in dt is less than 1/1000 of the mean dt, i.e.:

```python
dt = np.diff(timestamps)
((np.max(dt) - np.min(dt))/np.mean(dt)) <  (1/1000)
```

@luiztauffer what do you think, would this cover the relevant use-cases?

relevant to https://github.com/ben-dichter-consulting/buffalo-lab-data-to-nwb/issues/24, https://github.com/ben-dichter-consulting/buffalo-lab-data-to-nwb/issues/23

**Comment by bendichter** [comment]
This would require some additional code outside the GUI for the actual conversion code to run this test and return the results

**Comment by luiztauffer** [comment]
The GUI usually does not open the data files before execution of conversion, so it wouldn’t be able to tell if rate is available. It could be informed by the user through `metafile.yml` rate value though.
I see two scenarios:

1 – Best practices always enforced: In this case the conversion functions will always be responsible to choose how to store time information, we could use your <1/1000 rule on that for example. In this scenario user could still pass `rate` and `t0` through metafile if wanted, and we would remove the boolean checkbox option for timestamps.

2 – User-defined format: we leave it up to the user to decide how it’s gonna be stored (maybe unless your <1/1000 rule is broken for rate option, for example). Then a radiobox with these three options in the GUI, where auto would do the best-practices. The metafile.yml would have a field `time_control` with three possible string options ‘timestamps’, ‘rate_t0’, ‘auto’, or similar names.

**Comment by CodyCBakerPhD** [comment]
@bendichter @luiztauffer Is this still active?

**Comment by CodyCBakerPhD** [comment]
@bendichter @luiztauffer GUI no longer seems to work, can this be closed?
