### ISSUE TITLE
NWBConverter class

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#13]
Let's try to create an `NWBConverter` class to be used with loaded metadata. This class can be extended for the individual labs to handle their specific data types. That way the code will be centralized and reused instead of copied for each repo, and this will provide a structure that can be relied upon across tools. I have started this process in https://github.com/NeurodataWithoutBorders/nwbn-conversion-tools/blob/master/nwbn_conversion_tools/converter.py. Can we try to use this approach for the Jaeger lab conversion project?

**Comment by bendichter** [comment]
example usage: https://github.com/ben-dichter-consulting/tolias-lab-to-nwb/blob/master/tolias_lab_to_nwb/convert.py

**Comment by luiztauffer** [comment]
should we substitute this Issue by a guidelines document somewhere in the repo?
Something like "how to create new converters", instructing the use of NWBConverter class and maybe listing it's basic methods

**Comment by bendichter** [comment]
@luiztauffer that sounds like a great idea!

**Comment by bendichter** [comment]
The GUI should call the `run_conversion` method of the class instead of looking for the `run_conversion` method inside a given path

**Comment by luiztauffer** [comment]
this is outdated, closing it now
