### ISSUE TITLE
new version release

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-conversion-tools#140]
Depending on:
- [x] https://github.com/SpikeInterface/spikeextractors/pull/571
- [x] https://github.com/SpikeInterface/spiketoolkit/pull/440
- [x] https://github.com/catalystneuro/nwb-conversion-tools/pull/126
- [x] https://github.com/SpikeInterface/spikeextractors/issues/590
- [x] https://github.com/SpikeInterface/spiketoolkit/issues/463
- [x] new release of roiextractors (https://github.com/catalystneuro/nwb-conversion-tools/issues/135)
- [x] new release of spikeextractors (https://github.com/SpikeInterface/spikeextractors)
- [x] new release of spikesorters (https://github.com/SpikeInterface/spikesorters)
- [x] new release of spiketoolkit (https://github.com/SpikeInterface/spiketoolkit)

@bendichter @alejoe91 @CodyCBakerPhD @Saksham20 
trying to keep track here of what changes should be incorporated in other packages version releases before the most recent changes in **nwb-conversion-tools** can be released. Feel free to edit this list

**Comment by Saksham20** [comment]
@alejoe91 there is a small dependency issue with spikeextractors package on pip:
https://github.com/SpikeInterface/spikeextractors/issues/590

**Comment by Saksham20** [comment]
will be releasing the latest roiextractors on pypi soon https://github.com/catalystneuro/roiextractors/pull/80

**Comment by CodyCBakerPhD** [comment]
v0.7.0 was released a few days ago - closing this
