### ISSUE TITLE
Support Axona data conversion to NWB (add AxonaDataInterface)

### ISSUE THREAD

**Issue by sbuergers** [catalystneuro/nwb-conversion-tools#165]
I want to create an AxonaDataInterface to support converting [Axona data](http://space-memory-navigation.org/DacqUSBFileFormats.pdf) to NWB format. 

This should be possible for both raw, continuous data and unit data from Axona. 
I will implement them in that order.

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by CodyCBakerPhD** [comment]
@sbuergers Sounds great! We'll take it one PR at a time.

- [ ] Raw ([PR #166](https://github.com/catalystneuro/nwb-conversion-tools/pull/166))
- [ ] Processed units

**Comment by CodyCBakerPhD** [comment]
@sbuergers So on the processed units part, will that be in a separate PR? I think I might have seen that it was still in progress on spikeextractors

**Comment by sbuergers** [comment]
@CodyCBakerPhD Yes, that will be in a separate PR. For the moment it might not even be needed, since the conversion to NWB should work with the standard converter from spikeextractors. Will have to see. I will update it here if I start it.

**Comment by CodyCBakerPhD** [comment]
Is it a spikeinterface pipeline that appends file with write_sorting at the end? Or are they data files that have to be read and converted (even with just write_sorting)? I ask because occasionally that second option may be worthy of an interface of its own if there are unit properties (similar to channel properties for ecephys) to be included as metadata.

**Comment by sbuergers** [comment]
Yes, there is a spikeinterface pipeline with a `write_sorting` and `write_recording` at the end. I agree that it would be nice to have the UNIT data also be part of axonadatainterface to 1. keep everything together, 2. keep it independent of spikeinterface if that is ever needed or useful, and 3. add additional metadata that the spikeinterface method does not provide like you say. 

That being said, there are other parts of this conversion project that are more pressing, and this might not strictly be necessary. Hence, I will get to this possibly after finalizing the TINT conversion if there are still hours left and/or if we decide that it is really needed after all.

**Comment by CodyCBakerPhD** [comment]
If it's a spikeinterface pipeline then the sorting is simply handled through there, we don't offer data interfaces for in-environment arbitrary SortingExtractor objects (thought have run into this consideration before). Hence the main NWBConverter class is strictly for data that has already been written to files of propriety formats (the chief one being the Axona, which you have now completed).

I'll therefore close this issue with the completition of [PR #166](https://github.com/catalystneuro/nwb-conversion-tools/pull/166).

**Comment by sbuergers** [comment]
The hope is that we now have enough converters to satisfy a variety of conversions from Axona data to NWB with mixes of

*  Raw data
*  Unit data
*  Position data
*  EEG / EGF data

**Comment by CodyCBakerPhD** [comment]
> I also tried to implement a converter for `intan` data based on the existing `intandatainterface`, but this currently still fails.

Can you open a separate issue describing what's going on with the `intan` interface?

**Comment by sbuergers** [comment]
Yes! https://github.com/catalystneuro/nwb-conversion-tools/issues/229

**Comment by CodyCBakerPhD** [comment]
Closed by PR #227
