### ISSUE TITLE
Set Python >=3.7

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-conversion-tools#169]
## Description

For Python versions < 3.7 the datetime module has no attribute `fromisoformat`, this error happens on run_conversion:

```python
/media/luiz/storage/Github/nwb-conversion-tools/nwb_conversion_tools/nwbconverter.py in run_conversion(self, metadata, save_to_file, nwbfile_path, overwrite, nwbfile, conversion_options)
    140                     nwbfile = io.read()
    141                 elif nwbfile is None:
--> 142                     nwbfile = make_nwbfile_from_metadata(metadata=metadata)
    143 
    144                 for interface_name, data_interface in self.data_interface_objects.items():

/media/luiz/storage/Github/nwb-conversion-tools/nwb_conversion_tools/conversion_tools.py in make_nwbfile_from_metadata(metadata)
     59     # convert ISO 8601 string to datetime
     60     if isinstance(nwbfile_kwargs.get("session_start_time", None), str):
---> 61         nwbfile_kwargs["session_start_time"] = datetime.fromisoformat(metadata["NWBFile"]["session_start_time"])
     62     return NWBFile(**nwbfile_kwargs)
     63 

AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

I was using 3.6 because of one specific sorter (tridesclous maybe, but I can't remember exactly), but I feel we could actually fix Python to be >=3.7, since these sorters installation limitations are being dealt with with hither
@bendichter @CodyCBakerPhD @alejoe91 thoughts?

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by CodyCBakerPhD** [comment]
How would we fix or pin this in any way other than adding it to a couple places in the documentation/readme? It's not a thing we can pin in requirements per se as far as I know.

Note that the closest we come to an algorithmic way of guaranteeing it is in the [environment file for the package](https://github.com/catalystneuro/nwb-conversion-tools/blob/master/make_env.yml), which by the readme is the one environment for which we can guarantee everything works.

Also, I'm familiar with how certain spike sorters require very particular environment configurations, but can you not install it in that environment and then run the actual spike sorting pipeline and NWB conversion through a different environment by pointing the installation path in `spikesorters` to the other environment location?

**Comment by luiztauffer** [comment]
@CodyCBakerPhD  yes, I meant on the environment package and on README
But also if anyone is constrained to Python < 3.7 due to other requirements, this should serve as an alert

**Comment by luiztauffer** [comment]
how can you point to the specific path of installation?

**Comment by CodyCBakerPhD** [comment]
example: `WaveClusSorter.set_waveclus_path(...)`

In general, `NameOfSorter.set_sorter_name_path(...)`

**Comment by CodyCBakerPhD** [comment]
The environment file already specifies our supported version of python. Can you add the rest of the alerts to the documentation?
