### ISSUE TITLE
write_as_lfp argument

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-conversion-tools#170]
@CodyCBakerPhD is there any reason for making `write_as_lfp=False`?
Before we had it as an optional argument on `run_conversion()`

https://github.com/catalystneuro/nwb-conversion-tools/blob/54608fd49a7eff977cfb9d69d5cd73e90e78e927/nwb_conversion_tools/baserecordingextractorinterface.py#L113-L122

**Comment by CodyCBakerPhD** [comment]
Because the BaseLFPInterface exists for LFP data. The BaseRecordingInterface is for non-processed data. This distinguishes the two.

**Comment by luiztauffer** [comment]
ah I see... I think I missed it. 
Shouldn’t we then have a more general class for processed ecephys, a `BaseProcessedInterface` instead of `BaseLFPInterface` ? That would serve for any filtered data, including high-pass (used for sorting)

**Comment by CodyCBakerPhD** [comment]
The BaseLFP is a special type of BaseRecording that overrides that field and in general serves to separate the discrepancy in sampling rates. They are both fundamentally RecordingExtractor data types, as would a high-pass version (though that, too, would belong in a separate class).

If and when we decide we want to support writing of the high-pass data, we would decide whether it would inherit from the base recording (and modify the spikeextractors stuff to support it) or benefit from a general processing class, which we currently don't have.
