### ISSUE TITLE
CED interface time offsets

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-conversion-tools#176]
The problem reported [here](https://github.com/catalystneuro/mease-lab-to-nwb/issues/34) revealed that signals in `smrx` files (CED interface) might have different time offsets.
To account for that, at least for `CEDRecordingInterface`, we could e.g. pass `starting_time` to `NwbRecordingExtractor.write_recording()`, we could probably do it through the metadata dict. 
I'm not sure how that might affect `CEDStimulusInterface`
@alejoe91 @CodyCBakerPhD

**Comment by CodyCBakerPhD** [comment]
Hm... so theoretically, different channels might have different starting times for their `ElectricalSeries`? That specifically could be interesting to deal with.

The `add_electrical_series` method has timestamp information directly tied to the recording extractor object like so
```
        if not use_times:
            eseries_kwargs.update(
                starting_time=recording.frame_to_time(0),
                rate=float(recording.get_sampling_frequency())
            )
        else:
            eseries_kwargs.update(
                timestamps=H5DataIO(
                    recording.frame_to_time(np.arange(recording.get_num_frames())),
                    compression="gzip"
                )
            )
```
and so I'm not crazy about letting it be overridden via metadata or as an argument. Instead, the proper approach within the API would be to ensure the frame to time information is set/retrieved correctly in the extractor object itself, likely through the use of a `SubRecordingExtractor`.

**Comment by luiztauffer** [comment]
The smrx files might contain electrophys + behavioral + stimuli + experimenmter actions. In the 3 files I looked into, each of these could have its own offset time (as given by sonpy `FirstTime()` function) but all electrophys channels shared the same time offset

> Instead, the proper approach within the API would be to ensure the frame to time information is set/retrieved correctly in the extractor object itself, likely through the use of a SubRecordingExtractor.

I agree

**Comment by CodyCBakerPhD** [comment]
@luiztauffer Sounds good - looks like those changes were merged to spikeextractors core. If there isn't anything more to do about this over here, is the issue good to close?
