### ISSUE TITLE
NWBConverter's get_metadata() for DyanamicTable data interfaces

### ISSUE THREAD

**Issue by Saksham20** [catalystneuro/nwb-conversion-tools#177]
For current implementation of `NWBConverter.get_metadata()` , itloops over all the `datainterface `classes and updates a master metadata dict [like here](https://github.com/catalystneuro/nwb-conversion-tools/blob/918b408fc631329895154a2b767dc79cd5c83b5f/nwb_conversion_tools/nwbconverter.py#L165): I'm having a problem for datainterface child classes that want to update an existing DyanamicTable in nwbfile. 
Specifically, for `Electrodes`: I have 2 datainterface classes, the 1st of which creates an `Electrodes` with 96 columns with custom data like so: 
```python
metadata["Ecephys"]["Electrodes"] = [
            dict(name="filtering", description="filtering", data=["1000Hz"] * 192),
            dict(
                name="group_name",
                description="electrode group name",
                data=['PMd array'] * 96,
            ),
            dict(name='location',
                 description='location',
                 data=['Pre-Motor Cortex, dorsal'] * 96)
        ]
```
Creates okay, now the 2nd one has the same colnames with different data to append to the `Electrodes`:
```python
metadata["Ecephys"]["Electrodes"] = [
            dict(name="filtering", description="filtering", data=["1000Hz"] * 192),
            dict(
                name="group_name",
                description="electrode group name",
                data=['M1 array'] * 96, #difference here
            ),
            dict(name='location',
                 description='location',
                 data=['M1 Motor Cortex'] * 96) #difference here
        ]
```
this does not work as the  `NWBConverter.get_metadata()`'s `dict_deep_update()` creates: 
```python
etadata["Ecephys"]["Electrodes"] = [
            dict(name="filtering", description="filtering", data=["1000Hz"] * 192),
            dict(
                name="group_name",
                description="electrode group name",
                data=['PMd array'] * 96,
            ),
            dict(name='location',
                 description='location',
                 data=['Pre-Motor Cortex, dorsal'] * 96),
            dict(name="filtering", description="filtering", data=["1000Hz"] * 192),
            dict(
                name="group_name",
                description="electrode group name",
                data=['M1 array'] * 96, #difference here
            ),
            dict(name='location',
                 description='location',
                 data=['M1 Motor Cortex'] * 96) #difference here
        ]
```
So it essentially appends the list. And when the `NWBConverter.run_conversion()` calls the `data_interface_object.run_conversion()` with this master metadata, the child data interface sees this and does not convert correctly. I'm using the `BlackRockDataInterface `to populate the `Electrodes` and even with the offset `extractor._channel_ids`, [on this line](https://github.com/catalystneuro/spikeextractors/blob/7716cff0e64ac3f97bc85b445b1eeb97be4372a0/spikeextractors/extractors/nwbextractors/nwbextractors.py#L602) it pulls the 0:95 elements repeatedly. 
Essentially, the `Electrodes` in the nwbfile does have 192 columns but `nwbfile.electrodes['group_name'] is `['M1 array'] * 192` while I would like: `['PMd array'] * 96 + ['M1 array'] * 96`.

I could think of some possibilities to avert this:

1.  [On this line](https://github.com/catalystneuro/nwb-conversion-tools/blob/918b408fc631329895154a2b767dc79cd5c83b5f/nwb_conversion_tools/nwbconverter.py#L165), we could do: `metadata=data_interface.get_metadata()`. But this in a way reduces the functionality as the user cannot then override this. It may make sense thus to implement a `set_metadata()` method in data interfaces in general, which can be used for overrides in custom conversion scripts. 
2. Intelligent dict_deep_update() for a dynamic table: appends all data within the data field only (so in this case it would become something like: 
```python
metadata["Ecephys"]["Electrodes"] = [
            dict(name="filtering", description="filtering", data=["1000Hz"] * 192),
            dict(
                name="group_name",
                description="electrode group name",
                data=['PMd array'] * 96 + ['M1 array'] * 96,
            ),
            dict(name='location',
                 description='location',
                 data=['Pre-Motor Cortex, dorsal'] * 96 + ['M1 Motor Cortex'] * 96)
        ]
```
The datainterface could then look for the length of the existing `Electrodes` table and pick and populate correct data from `metadata["Ecephys"]["Electrodes"][0]['data']`. 1st datainterface: `metadata["Ecephys"]["Electrodes"][0]['data'][:96]` and the 2nd one : `metadata["Ecephys"]["Electrodes"][0]['data'][97:193]`

**Comment by Saksham20** [comment]
> which is why metadata is never required nor automatically pulled if missing in the main converter as per suggestion (a). Basically, the user is always responsible for ensuring the correct metadata format prior to running conversion.

In this case, I think its impossible to call NWBConverter.run_conversion() correctly: even if the user were to manually update the electrodes table like so:
```python
metadata["Ecephys"]["Electrodes"] = [
            dict(name="filtering", description="filtering", data=["1000Hz"] * 192),
            dict(
                name="group_name",
                description="electrode group name",
                data=['PMd array'] * 96 + ['M1 array'] * 96,
            ),
            dict(name='location',
                 description='location',
                 data=['Pre-Motor Cortex, dorsal'] * 96 + ['M1 Motor Cortex'] * 96)
        ]
```
`NwbRecordingExtractor.write_recording()`'s `write_electrodes()` will always loop over the first 96 indices of the data and fill in that value even if the `channel_ids `are changed. Thats why the mt final `Electrodes` table, though may be of correct length (96*2), it will only have 'M1 array' as the 192 group_names. 
for conversion's sake i have currently changed the `NWBConverter.run_conversion()` line on looping over datainterfaces' `run_conversion()` to pull metadata for each converter instead. : here line 165 replacing with `metadata=data_interface.get_metadata()`.

I think having a `set_metadata()` within each class could be the only way for a user to change the default class's metadata and make a conversion, with the above api change for argument to converter.run_conversion()

**Comment by luiztauffer** [comment]
@Saksham20 just bo be sure, are you using the most recent changes in [here](https://github.com/catalystneuro/nwb-conversion-tools/pull/174)?

**Comment by luiztauffer** [comment]
**On metadata auto-formation**
For now the user has to edit a python dictionary manually, so I like @Saksham20 idea of having a `set_metadata()` that could facilitate that somehow.

I agree with @CodyCBakerPhD that this looks quite particular to this converter, so it would probably be better to just edit `MyConverter.get_metadata()`. If it’s a situation that will likely happen again, I guess we could have a special treatment for Electrodes (and potentially other tables). As of now I think Electrodes is the only field for which we can pass data in the metadata in such a way, so maybe it does deserve special treatment.

**On write_recording**
Assuming you have a complete metadata dictionary (with all correct Electrodes data), I think the electrodes table in the nwbfile will be created on the first `DataInterface.run_coversion()` call, and the second call should identify it exists and use it. By the way, I think different dicts related to the same table (`filtering`, `group_name` and `location` in your example) should carry the same number of elements, in this case: `dict(name="filtering", description="filtering", data=["1000Hz"] * 96)`

Now the problem would be to assign the proper rows indexes for each ElectricalSeries (which will be written by different DataInterfaces). We could use the key `electrode_table_region` in the ElecetricalSeries metadata to pass the list of indexes for which the electrode_table_region will be created for that specific ElectricalSeries. This would need to be implemented on `NwbRecordingExtractor.write_electrodes()` as @Saksham20 suggested, but it should be simple to do.

This should also require some modification on ElectricalSeries schema that comes from `get_schema_from_hdmf_class()`

**Comment by CodyCBakerPhD** [comment]
> `NwbRecordingExtractor.write_recording()`'s `write_electrodes()` will always loop over the first 96 indices of the data and fill in that value even if the `channel_ids `are changed. Thats why the mt final `Electrodes` table, though may be of correct length (96*2), it will only have 'M1 array' as the 192 group_names.

@Saksham20 [Lines 549-594 ](https://github.com/catalystneuro/spikeextractors/blob/master/spikeextractors/extractors/nwbextractors/nwbextractors.py#L549-L594) of `add_electrodes` look like they should loop over and index the metadata based on whatever the channel ids are for each extractor. Hence why that internal `channel_ids` hack specific to your extractor should work, and why your manually specified metadata looks as if it should work too.

If you are saying that you run the conversion and find, in the output NWBFile, that the `group_name` isn't correctly assigned for each electrode (if they are all "M1 array"), could you add a print statement after [line 549](https://github.com/catalystneuro/spikeextractors/blob/master/spikeextractors/extractors/nwbextractors/nwbextractors.py#L549) (or wherever the line may be in your version) for checking the iteration of the channel ids?

**Comment by Saksham20** [comment]
i did and channel ids are correctly offset. the problem is on [line 567](https://github.com/catalystneuro/spikeextractors/blob/master/spikeextractors/extractors/nwbextractors/nwbextractors.py#L567)
and [line 591](https://github.com/catalystneuro/spikeextractors/blob/master/spikeextractors/extractors/nwbextractors/nwbextractors.py#L591),
it uses the index of the channel_ids (from the enumerate in the for loop)

**Comment by CodyCBakerPhD** [comment]
Ahh, I see the issue now. I'm thinking that allowing the data field to be a dictionary resolving the mapping should fix the issue. Probably best to build this in a future PR once the current round of fixes gets merged to keep things from snowballing too much over there.

Looking towards SpikeInterface2, both of these would be great to set as channel properties in the extractor itself, but alas it does not support string named groups at the moment.

**Comment by Saksham20** [comment]
Yes, we could route all this custom column addition to the `Electrodes `via adding them as channel properties, but I see a problem there: [on line 640](https://github.com/catalystneuro/spikeextractors/blob/6666b5c3b189f314b24b6c33b8ee91c67403ee9f/spikeextractors/extractors/nwbextractors/nwbextractors.py#L640), it creates a column after adding rows, so if a datainterface wants to append to `Electrodes` the subsequent `nwbfile.add_electrode()` would also need to have that channel property as a named argument.

But yeah, all this could be implemented and discussed in a future PR

**Comment by CodyCBakerPhD** [comment]
Yeah channel props wouldn't work right now for two reasons: a) the group field can only be an integer, not a string, and b) the default columns aren't allowed to be overridden by channel groups (has some legacy reasons for this related to discrepancies between what we consider a `location' and what spikeextractors conders a `location' property as I recall.

Just thinking of that approach as being the proper way around the light vs. heavy metadata problem.
