### ISSUE TITLE
remove fixed dependency for juptyer-client version

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-conversion-tools#18]
depending on resolution of 
https://github.com/jupyter/jupyter_client/issues/523

**Comment by bendichter** [comment]
@luiztauffer has this been resolved?

**Comment by bendichter** [comment]
@luiztauffer maybe this was causing the import error for @Saksham20?

**Comment by luiztauffer** [comment]
i can't be it, I fixed the `jupyter-client==5.3.4` in setup.py

**Comment by luiztauffer** [comment]
The fixing of jupyter-client package is not optimal though, because they already crossed > 6.0
So let's keep this issue here to remind me to test new releases once they get it solved
