### ISSUE TITLE
Bring NwbSortingExtractor.write_sorting() functions to utils.spike_interface.py

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-conversion-tools#182]
Bring `se.NwbSortingExtractor.write_sorting()` functions to module [utils.spike_interface.py](https://github.com/catalystneuro/nwb-conversion-tools/blob/master/nwb_conversion_tools/utils/spike_interface.py)

**Comment by CodyCBakerPhD** [comment]
On it.
