### ISSUE TITLE
Standardize releases pipeline

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-conversion-tools#210]
We should standardize our releases pipeline. Right now, Github releases are usually not made prior to PyPI publishing and the github action for automatic PiPY publishing is not working.
I'm opening a PR where we can discuss possible ways of doing that.

**Comment by CodyCBakerPhD** [comment]
So, for v0.8.1, you had to manually upload that to PyPI, right? The GitHub release didn't automatically handle it?

**Comment by luiztauffer** [comment]
@CodyCBakerPhD that's right
