### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#24]
Add test for reading from recording extractor and writing

Use https://github.com/SpikeInterface/spikeextractors/tree/master/spikeextractors/example_datasets for generating fake data

Use actions to set up continuous integration [similar to NWBWidgets](https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets/tree/master/.github/workflows)

**Comment by bendichter** [comment]
@Armin12 can you help with this?

**Comment by Armin12** [comment]
Sure!

**Comment by yarikoptic** [comment]
and let me and/or @mvdm know if you would like some real data for neuralynx systems, we could provide! ;)

**Comment by bendichter** [comment]
What's the best way to integrate real data with CI?

**Comment by yarikoptic** [comment]
I guess it all depends on the sizes etc.  We could setup some datalad datasets (could even store data within github lfs while sizes allow for free storage, see [datalad handbook for an example](http://handbook.datalad.org/en/latest/basics/101-138-sharethirdparty.html#use-github-for-sharing-content)), and use datalad to get desired files from the cloudy cloud.

**Comment by yarikoptic** [comment]
here is e.g. one example in heudiconv where we do some regression testing using data we fetch using datalad (from my server I believe): https://github.com/nipy/heudiconv/blob/ca402a9fa701551bf2c74f72d77223aaad7e5d68/heudiconv/tests/test_regression.py
