### ISSUE TITLE
File and Directory annotations not showing up on schema

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-conversion-tools#244]
## Description

**Problem 1:**
PR #237 is supposed to auto infer File or Directory type of paths within source_data_schema from init, but it doesn't seem to be working.

**Problem 2**
This is the weirdest: after re-running the same Notebook cell, the following error track shows, apparently the type string is being changed somehow.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-6d29f0927059> in <module>
----> 1 OpenEphysRecordingExtractorInterface.get_source_schema()

/media/luiz/storage/Github/nwb-conversion-tools/nwb_conversion_tools/datainterfaces/ecephys/openephys/openephysdatainterface.py in get_source_schema(cls)
     18         """Compile input schema for the RecordingExtractor."""
     19         source_schema = get_schema_from_method_signature(
---> 20             class_method=cls.__init__, exclude=["recording_id", "experiment_id", "stub_test"]
     21         )
     22         source_schema["properties"]["folder_path"]["description"] = "Path to directory containing OpenEphys files."

/media/luiz/storage/Github/nwb-conversion-tools/nwb_conversion_tools/utils/json_schema.py in get_schema_from_method_signature(class_method, exclude)
    124                     else:
    125                         raise ValueError(
--> 126                             f"No valid arguments were found in the json type mapping {arg} for parameter {param}"
    127                         )
    128                     if arg == FilePathType:

ValueError: No valid arguments were found in the json type mapping ~FolderPathType for parameter folder_path: ~FolderPathType
```

## Steps to Reproduce
```
from nwb_conversion_tools import OpenEphysRecordingExtractorInterface
OpenEphysRecordingExtractorInterface.get_source_schema()
```

## Environment

    Python Executable: Conda or Python
    Python Version: Python 3.7.10
    Operating System: Linux
    PyNWB Version: master branch    

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by luiztauffer** [comment]
**Update**
The weird **Problem 2** happens with the autoreload in Jupyter, whenever I modify anything in the code (e.g. add a print) and re-run the cell.  @CodyCBakerPhD do you have any idea what in our `TypeVar` usage might be causing this?

**Comment by CodyCBakerPhD** [comment]
For Problem #2 can you insert a print statement into [line 103](https://github.com/catalystneuro/nwb-conversion-tools/blob/master/nwb_conversion_tools/utils/json_schema.py#L103) of the `json_schema` code and post what it looks like before and after your reload?

**Comment by luiztauffer** [comment]
@CodyCBakerPhD , I'm printing `arg` here:
![image](https://user-images.githubusercontent.com/24541631/131526842-b4b4b539-ae02-4773-a11f-40ce2e2e8414.png)

Here's a summary of what happens:
![image](https://user-images.githubusercontent.com/24541631/131526593-f560f8fd-5180-46cb-87ce-3d47d2036f10.png)

**Comment by luiztauffer** [comment]
Here is it, doesn't seem to be the problem you expected:

![image](https://user-images.githubusercontent.com/24541631/131669974-20be117a-2aae-44e2-bd7b-3ed7fd0e3a99.png)

**Comment by luiztauffer** [comment]
The only problem reported online involving TypeVar and autoreload I could find hints to it being a Python version problem. 
It doesn't seem to be the case here, I reproduced the error using python 3.7.10 and 3.8.11
