### ISSUE TITLE
missing device

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#27]
https://github.com/catalystneuro/nwb-conversion-tools/blob/f59cdfdf5a9236e6d4f9ca20e90fa792c2c37dd0/nwb_conversion_tools/converter.py#L124-L137

This will lead to an error when device is used before being defined on line 135

**Comment by luiztauffer** [comment]
Devices should be created on `__init__` here:
https://github.com/catalystneuro/nwb-conversion-tools/blob/f59cdfdf5a9236e6d4f9ca20e90fa792c2c37dd0/nwb_conversion_tools/converter.py#L37-L41

So I see two scenarios:
1. We're not covering for a group which might also use Device. In this case it's just adding it to line `for domain in ('Icephys', 'Ecephys', 'Ophys'):`
2. The user did not define the Device in the yaml file. In this case what you suggest? We raise an error with the prints in lines 127-128?

**Comment by luiztauffer** [comment]
this is outdated, closing it
