### ISSUE TITLE
increase test coverage

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#277]
right now, test coverage is reported as 66%. Let's try to bump that up a bit.

**Comment by bendichter** [comment]
It's tricky because brpylib.py doesn't have a license associated with it. Ideally we would ask Blackrock to host it themselves

**Comment by CodyCBakerPhD** [comment]
- [ ] Thorough tests of append mode: https://app.codecov.io/gh/catalystneuro/nwb-conversion-tools/blob/main/nwb_conversion_tools/nwbconverter.py
- [ ] Basic assertion tests for core classes

**Comment by CodyCBakerPhD** [comment]
NeuroConv now has 90% coverage! Thanks @h-mayorquin and @weiglszonja for all your work adding tests!
