### ISSUE TITLE
ABF interface should be able to take in multiple ABF files and organize them 

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#295]
Briefly describe the needed feature as well as the reasoning behind it

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm trying to achieve [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by CodyCBakerPhD** [comment]
@luiztauffer I believe this is taken care of now in #362, correct?

**Comment by luiztauffer** [comment]
@CodyCBakerPhD that's correct, I included it in the PR description
