### ISSUE TITLE
GIN tests gap: Mac OS X for sonpy

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/nwb-conversion-tools#303]
## Description

When we added CED tests to our `test_gin.py` collection, the CI revealed some weird issue with importing the `sonpy` package seen here: https://github.com/catalystneuro/nwb-conversion-tools/runs/4358475697?check_suite_focus=true

The runner reports the package installed correctly, without issue, but still raises the lazy check for that interface only, indicating some other `ImportError`.

For now, it's simply manually disabled in the `test_gin` to ignore if running on mac.

## Steps to Reproduce

I don't have quick immediate access to a Mac device to test this right at the moment, so anyone that does is welcome to try

```
conda create -n test_sonpy python=3.7  # since that's what our CI runs  on
conda activate test_sonpy
# from nwb-conversion-tools
pip install -r requirements-full.txt
pip install -e .

python
> import sonpy
```

## Environment

Master branch of nwb-conversion-tools, full CI runner specification (`requirements-full.txt`).
    

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by bendichter** [comment]
```
>>> import sonpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bendichter/opt/miniconda3/envs/test_sonpy/lib/python3.7/site-packages/sonpy/__init__.py", line 10, in <module>
    import sonpy.darwin.sonpy as lib
ImportError: Python version mismatch: module was compiled for Python 3.8, but the interpreter version is incompatible: 3.7.11 (default, Jul 27 2021, 07:03:16) 
[Clang 10.0.0 ].
```

**Comment by CodyCBakerPhD** [comment]
So weird that the linux version was definitely compiled and runs on 3.7.

I'll add a specific assertion for this at the code level to be more informative to the user now that we understand the reason (and to the CI by proxy).
