### ISSUE TITLE
Dict deep update default behavior transforms list into dics

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/nwb-conversion-tools#314]
## Description
Working in some conversion I was getting a validation error for failing to provide an array for some properties. Digging deeper into it it seems that when the metadata from `NeuroscopeLFPInterface` and that from `CellExplorerSortingInterface` are combined a list form the latter (specifically `UnitProperties`) is somehow trimmed and transform into a list.

## Minimal example
Here a minimal example that indicates the problem

```python

metadata_from_neuroscope_lfp = {
    "Ecephys": {
        "Device": [{"name": "Device_ecephys", "description": "no description"}],
        "ElectrodeGroup": [
            {"name": "Group1", "description": "Group1 electrodes.", "location": "", "device": "Device_ecephys"},
            {"name": "Group2", "description": "Group2 electrodes.", "location": "", "device": "Device_ecephys"},
            {"name": "Group3", "description": "Group3 electrodes.", "location": "", "device": "Device_ecephys"},
        ],
        "ElectricalSeries_lfp": {"name": "LFP", "description": "Local field potential signal."},
        "Electrodes": [
            {"name": "shank_electrode_number", "description": "0-indexed channel within a shank."},
            {"name": "group_name", "description": "The name of the ElectrodeGroup this electrode is a part of."},
        ],
    }
}

metadata_from_cellexplorer_sorting = {
    "NWBFile": {"session_id": "20170201_72um_432um_merge"},
    "Ecephys": {
        "UnitProperties": [
            {"name": "clu_id", "description": "0-indexed id of cluster identified from the shank."},
            {"name": "group_id", "description": "The electrode group ID that each unit was identified by."},
            {"name": "location", "description": "Brain region where each unit was detected."},
        ]
    },
}

print(dict_deep_update(metadata_from_neuroscope_lfp, metadata_from_cellexplorer_sorting))
```
The script outputs the following:

```javascript
{'Ecephys': {'Device': [{'name': 'Device_ecephys',
    'description': 'no description'}],
  'ElectrodeGroup': [{'name': 'Group1',
    'description': 'Group1 electrodes.',
    'location': '',
    'device': 'Device_ecephys'},
   {'name': 'Group2',
    'description': 'Group2 electrodes.',
    'location': '',
    'device': 'Device_ecephys'},
   {'name': 'Group3',
    'description': 'Group3 electrodes.',
    'location': '',
    'device': 'Device_ecephys'}],
  'ElectricalSeries_lfp': {'name': 'LFP',
   'description': 'Local field potential signal.'},
  'Electrodes': [{'name': 'shank_electrode_number',
    'description': '0-indexed channel within a shank.'},
   {'name': 'group_name',
    'description': 'The name of the ElectrodeGroup this electrode is a part of.'}],
  'UnitProperties': {'name': 'location',
   'description': 'Brain region where each unit was detected.'}},
 'NWBFile': {'session_id': '20170201_72um_432um_merge'}}
```
Notice how `UnitProperties` is not a list anymore.

## Environment
I am running this with the latest version of master installed with `pip install -e . ` in my environment. 
    

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by CodyCBakerPhD** [comment]
Attn: @Saksham20; these errors were not present prior to the merge of #291

**Comment by Saksham20** [comment]
thanks @h-mayorquin for finding this bug! I have linked a PR that fixes this. Please try out the dict update with your minimal example and confirm. It works on my end.

**Comment by h-mayorquin** [comment]
@Saksham20 
The bug fix on the pull request works for me. `UnitProperties` now is a list.
