### ISSUE TITLE
Extend CellExplorerInterface to MATLAB v7.3+

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/nwb-conversion-tools#318]
This would be a good first upstream PR from the Buzsaki project for @h-mayorquin, since he's already looked into it a bit.

Basically, the current `CellExplorerSortingInterface` only strictly supports reading and data retrieval from MATLAB files through `scipy.io.loadmat`.

This can be extended to the other MATLAB file versions with `hdf5storage.loadmat`. It will change the way data is retrieved from many of the keys, however, so I've added a task list to get started.

**Describe the solution you'd like**

- [x] Find two good example `.mat` files for this task; one that is readable in `scipy`, one that is not. We've already found some like this in Tingley, just need to report exact session IDs here for clarity.
- [ ] The neo team currently has a PR on GIN for `scipy` readable CellExplorer files; when you find a good example of a `hdf5storage` one, send it my way and I'll stub it and send it their way.
- [ ] Add GIN tests for the CellExplorerSortingInterface acting on the `scipy` readable files.
    -  [ ] When the `hdf5storage` files are added after stubbing, add tests for them as well.
- [x] Make a spikeextractors PR for the `sessionInfo.mat` file access.

For later, when we find a `.cellinfo` file with these properties...
- [ ] At first attempt to load the file in the Interface, do a `try/except` to determine the file version and track the result through an attribute, _e.g._, `self.matlab_file_version`.
- [ ] Based on the result of that attribute, for each data retrieval the interface performs, find the analog that perfectly matches it for the `hdf5storage` version.
    - Technically, this would be way more efficient if we made a specialized reader class for all MATLAB files that always handled data access from all source files through the same API, but this is a tad complicated for a first PR. We can always refactor it a bit later to reduce code.

As always, do not hesitate to reach out if you ever have a question, no matter how small.

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by h-mayorquin** [comment]
The problematic files are the `sessionInfo.mat` which are in the two types for formats.
    Old format:
`"/shared/catalystneuro/Buzsaki/TingleyD/DT8/20170220_216um_1944um_170220_192456/20170220_216um_1944um_170220_192456.sessionInfo.mat"`

New format
        `"/shared/catalystneuro/Buzsaki/TingleyD/DT2/DT2_rPPC_rCCG_3468um_1216um_20160225_160225_130701/DT2_rPPC_rCCG_3468um_1216um_20160225_160225_130701.sessionInfo.mat"`

**Comment by h-mayorquin** [comment]
I don't understand the second point. The second file that I shared above (the one in the new format) that should be the one, right? Or are you talking about a `spikes.info` file?

**Comment by h-mayorquin** [comment]
I found a spikes.info file in new format (that is, unreadable by scipy). The files belong to the repository corresponding to the cell explorer paper and can be found in the globus data system:
/PetersenP/CellExplorerExampleData/MS22/Peter_MS22_180629_110319_concat/
@CodyCBakerPhD

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Very nice find! I remember having to use `hdfstorage` for most of that conversion, but I didn't update upstream interfaces at the time, just the local scripts. Will be nice to have it integrated.
