### ISSUE TITLE
Default behavior of stub_test=True

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/nwb-conversion-tools#320]
## Description
@Saksham20 Prior to the recent refactor, specifying `stub_test=True` in any `RecordingInterface` would simply clip the time values to something reasonably small to allow the rest of the conversion process to proceed quickly. However, the purpose of this design is to ensure that, by stubbing, we have altered as little of the conversion workflow as possible so that we can use quick stubbed testing to debug. Swapping from `stub_test=True` to `stub_test=False` should, in principle, not reveal any additional bugs aside from an odd condition related to the extraction/writing of the rest of the data values in the time series.

The [recent ephys refactor](https://github.com/catalystneuro/nwb-conversion-tools/blob/422740be88b01035a2732853b9cd18dd36463e38/nwb_conversion_tools/utils/si013nwbephyswriter.py#L43-L48) has changed this to automatically subset the channels as well, which in turn appears to alter the entire metadata loading behavior, which reveals some additional bugs that will be raised separately.

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by Saksham20** [comment]
@CodyCBakerPhD #324

**Comment by CodyCBakerPhD** [comment]
@Saksham20 #324 deals with remapping the writer class, as far as I can see; this issue is related to how channels are now additionally stubbed with frames when `stub_test=True` is specified, which can have other implications for testing in-development pipelines.

I don't see a reason to stub channels at all - even if you had 10,000 of them it wouldn't come close to a full second's worth of frames at normal `ecephys` resolutions; but channels often have critical metadata associated with them whereas individual frames do not.

**Comment by bendichter** [comment]
I can't really follow what the issue is here

**Comment by CodyCBakerPhD** [comment]
Before refactor, `stub_test=True` would only clip time. Now it clips time and channels.

When testing/developing full conversions with `stub_test` enabled, there are cases where there's metadata extraction/setting applied to assume all channels are present in the object, but these wouldn't show up until you disabled the stub.

The point to the `stub_test` method, in general, is to imitate a full conversion as much as possible with respect to functionality while still allowing it to finish very quickly.

**Comment by bendichter** [comment]
Oh, I agree it should only clip time.
