### ISSUE TITLE
Gain not propagated to final nwb files as a consequence of SubRecording extractor

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/nwb-conversion-tools#330]
## Description
I am running a conversion pipeline from the Buzsaki lab and I am finding that the gain is not propagated to either the LFP nor the raw data. For this I am using the `Neuroscope` data interfaces and I think the problem consists of two parts.

1) First, when the Neuroscope is instantiated the _init_function calls `subset_shank_channels` whose role is to remove non meaningful channels based on the XML file:
https://github.com/catalystneuro/nwb-conversion-tools/blob/0809bb4f845d2fdc7d8f85b8b953d9b4fafd7e32/nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py#L107-L111
`subset_shank_channels` in turn calls `se.SubRecordingExtractor` but this **does not inherit all the properties from the base recorder**:
https://github.com/catalystneuro/nwb-conversion-tools/blob/0809bb4f845d2fdc7d8f85b8b953d9b4fafd7e32/nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py#L23-L29
This means, that the new instance of the recording extractor ends without the appropriate gains even if those are correclly passed as an argument.

This issue can be solved quickly by adding a gain property to the auxiliar function already in place that adds the properties to the new `SubRecordingExtractor` after it is instantiated:
https://github.com/catalystneuro/nwb-conversion-tools/blob/0809bb4f845d2fdc7d8f85b8b953d9b4fafd7e32/nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py#L207-L210

I already tried a a patch in a local branch and that does propagates the gains to where they should be.
However,

2)  The second issue manifest itself when running stubs. The problem is that when running the conversion pipeline with `stub_test=True` the writer class re-instantiates the recording extractor again. The base recording extractor instantiates the writer class in the spot in the following place:
https://github.com/catalystneuro/nwb-conversion-tools/blob/0809bb4f845d2fdc7d8f85b8b953d9b4fafd7e32/nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py#L88-L99

 Which in turn ends up calling again `se.SubRecordingExtractor`. In my case, this is done through the `SI013NwbEphysWriter`:
https://github.com/catalystneuro/nwb-conversion-tools/blob/0809bb4f845d2fdc7d8f85b8b953d9b4fafd7e32/nwb_conversion_tools/utils/si013nwbephyswriter.py#L29-L39

There the `self._make_recording_stub()` is defined in the following way as you can see ends up calling `se.SubRecordingExtractor` :
https://github.com/catalystneuro/nwb-conversion-tools/blob/0809bb4f845d2fdc7d8f85b8b953d9b4fafd7e32/nwb_conversion_tools/utils/si013nwbephyswriter.py#L41-L43  

Which ends up with the gains being overwritten again. For this second issue I have not patched locally. I guess the solution can be like one, to add the extractor properties again after calling `se.SubRecordingExtractor`.

However, it seems that we would kill two birds with the same shot if somehow we manage to get `se.SubRecordingExtractor` to inherit all the properties of the parent extractor. Has this been try before and there are dragons lurking there that I don't know about? What do you think?
 
## Steps to Reproduce
TBD

## Environment
Runing the master branch from `nwb_conversion_tools` 

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by h-mayorquin** [comment]
It seems that to me that `se.SubRecordingExtractor` could be quickly patched by adding an optional flag to not run the two following lines:

https://github.com/catalystneuro/spikeextractors/blob/da5e799cf20e678d0a1a7b66b2da1c6d7fa0aee0/spikeextractors/subrecordingextractor.py#L34-L36

**Comment by CodyCBakerPhD** [comment]
Unfortunately, I think that would count as 'new feature' against the legacy status of that repo; the better option for us would be to make our own type of `CopyRecordingExtractor` for instance, that replicates much of the logic of the Sub (maybe even uses it partially) but fixes that one issue that causes us so many troubles.

Maybe the new `spikeinterface/spikeinterface` could have an option flag or something, though. What do you think @alejoe91 ?

**Comment by bendichter** [comment]
I'd rather not maintain a `CopyRecordingExtractor` class. Let's discuss with @alejoe91 before we start going down that sort of long path
