### ISSUE TITLE
movies question

### ISSUE THREAD

**Issue by paul-aparicio** [catalystneuro/nwb-conversion-tools#331]
Hello, I am trying to build a converter that has a recording, sorter and multiple movie files. I am having difficulty getting the movies part to work. Might there be an example of how to do this? Thanks!

**Comment by CodyCBakerPhD** [comment]
Hello @paul-aparicio, welcome to nwb-conversion-tools!

For using a `MovieInterface`, these are the important steps:

1. Make sure you have the `opencv-python` package (`pip install opencv-python`) as it is necessary for extracting not just frames (if not using `external_mode`) but also metadata such as framerate, number of frames, etc.
2. Import the `MovieInterface` from nwb-conversion-tools (`from nwb_conversion_tools import MovieInterface`) and add it to your converter's `data_interface_classes` dictionary, similar to any other interface
3. The `source_data` argument for this interface is `file_paths` and is a `list` of individual paths, each pointing to a separate movie file. If you only have one movie file, then this would be a list of a single element `source_data = dict(..., MovieInterface=dict(file_paths=["path_to_video_file.mp4"]))`
4a. The `conversion_options` are where this interface can get a tad complicated. Note that if you are intending your NWBFiles for ultimate upload to DANDI, you will likely want to keep the `external_mode` to it's default of `true`, which means what gets written to the NWBFile is a relative path to the movie file and not the actual frames themselves. The DANDI team is putting finishing touches on a method for allowing such external movie files to be uploaded alongside the NWBFiles, and should be done in the near future.
4b. The other important argument for the movie file is the `starting_times`; every time-dependent object in an NWBFile must be aligned to the `session_start_time` value, so if there's an offset or other delay, the `starting_times=[my_starting_time]` option specifies this increment in the timestamps for the object.
4c. To explore other `conversion_options`, just type `MovieInterface.run_conversion?` to view the documentation for the interface.

If you run into any issues, please post a full traceback and associated code so we can help debug it for you.

Best,
Cody Baker
Sr. Neuro-data Scientist, CatalystNeuro

**Comment by CodyCBakerPhD** [comment]
Hi @paul-aparicio, did this answer your question?

**Comment by paul-aparicio** [comment]
Yes, thank you for your response.
