### ISSUE TITLE
can we not automatically assign this?

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#354]
https://github.com/catalystneuro/nwb-conversion-tools/blob/d1c78a9048f10d635379195acff645bddd21647e/nwb_conversion_tools/utils/spike_interface.py#L1270

**Comment by CodyCBakerPhD** [comment]
You mean have it be a non-optional argument? Since it is required for writing an NWBFile, and the `write_*` methods are to work as standalone functions outside of an `NWBConverter` that would normally handle it.

**Comment by CodyCBakerPhD** [comment]
After discussion, this should now be a required argument of all `write_*` arguments, as well as `NWBConverter.run_conversion` if no associated `DataInterface` has auto-populated it from the source data.
