### ISSUE TITLE
Gain mismatch with the neuroscope and spikeinterface

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/nwb-conversion-tools#382]
## Description
This is to discuss an error that arises when a neuroscope recorder subsets some of its channels. In short, there is a shape mismastch between the channels gains inherited from the neuroscope recorder and the ones that are assigned to `spikeinterface`.  See the bottom of this issue for the error trace. In this case, the gain is propagated correctly but no the shape.

In more detail:
The problem occurs in the conversion of the recording extractors to a spike interface object in the `spike-interface` of `nwb-conversion-tools`. This is carred ou int `old_api_utils`:

https://github.com/SpikeInterface/spikeinterface/blob/ec7adf991835e851926c89adb3be7f1d97f8d629/spikeinterface/core/old_api_utils.py#L171-L198

The machinery in `old_ap_utils` correctly gets all the gains from the uppermost level of the original recording extractor (lines 189) but the new spikeinterface object is initiated with the number of channels in the recording extractor that was passed to it (see the arguments passed to the class in lines 172). This generates a size clash in in the new functions in charge of settings the properties as the shape of the two arrays don't match (lines 193).

Now, in this case for Neuroscope the channels are subset because we have some functions that remove the channels not related to neural data  in the `neuroscopedatainterface`:

https://github.com/catalystneuro/nwb-conversion-tools/blob/1bbefafa10e6b2d7b5daa67fc5d6f273bf13a487/nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py#L23-L33

So, some channels are removed by this function. Then, in the transformation from spikeextractor to spikeinterface the gains are extracted from the original channel but the new spikeinterface object inherits the number of channels from the subrecording creating a mismatch. 

What gives and what should be done? the gain values should indeed be extracted from the upermost level as it is the one that in fact holds the correct gain values. On the other hand, I think the shape should be broadcasted to be equal to that one in the subrecording as that is the one that will actually be written.

What do you think?
@CodyCBakerPhD @alejoe91 

Error trace:
```python
AssertionError                            Traceback (most recent call last)
~/development/buzsaki-lab-to-nwb/buzsaki_lab_to_nwb/tingley_code_septal/convert_tingley_septal.py in <module>
    126         metadata=metadata,
    127         conversion_options=conversion_options,
--> 128         overwrite=True,
    129     )
    130     print("Done with conversion")

~/development/nwb-conversion-tools/nwb_conversion_tools/nwbconverter.py in run_conversion(self, metadata, save_to_file, nwbfile_path, overwrite, nwbfile, conversion_options)
    170 
    171                 for interface_name, data_interface in self.data_interface_objects.items():
--> 172                     data_interface.run_conversion(nwbfile, metadata, **conversion_options.get(interface_name, dict()))
    173 
    174                 io.write(nwbfile)

~/development/nwb-conversion-tools/nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py in run_conversion(self, nwbfile, metadata, stub_test, starting_time, use_times, save_path, overwrite, write_as, write_electrical_series, es_key, compression, compression_opts, iterator_type, iterator_opts)
    179             compression_opts=compression_opts,
    180             iterator_type=iterator_type,
--> 181             iterator_opts=iterator_opts,
    182         )

~/development/nwb-conversion-tools/nwb_conversion_tools/utils/spike_interface.py in write_recording(recording, save_path, overwrite, nwbfile, starting_time, use_times, metadata, write_as, es_key, write_electrical_series, write_scaled, compression, compression_opts, iterator_type, iterator_opts)
   1013             iterator_type=iterator_type,
   1014             iterator_opts=iterator_opts,
-> 1015             write_electrical_series=write_electrical_series,
   1016         )
   1017     return nwbfile

~/development/nwb-conversion-tools/nwb_conversion_tools/utils/spike_interface.py in add_all_to_nwbfile(recording, nwbfile, starting_time, use_times, metadata, write_as, es_key, write_electrical_series, write_scaled, compression, compression_opts, iterator_type, iterator_opts)
    824         assert isinstance(nwbfile, pynwb.NWBFile), "'nwbfile' should be of type pynwb.NWBFile"
    825 
--> 826     add_electrodes_info(recording=recording, nwbfile=nwbfile, metadata=metadata)
    827 
    828     if write_electrical_series:

~/development/nwb-conversion-tools/nwb_conversion_tools/utils/spike_interface.py in add_electrodes_info(recording, nwbfile, metadata)
    751     """
    752     add_devices(nwbfile=nwbfile, metadata=metadata)
--> 753     add_electrode_groups(recording=recording, nwbfile=nwbfile, metadata=metadata)
    754     add_electrodes(recording=recording, nwbfile=nwbfile, metadata=metadata)
    755 

~/development/nwb-conversion-tools/nwb_conversion_tools/utils/spike_interface.py in add_electrode_groups(recording, nwbfile, metadata)
    169     assert isinstance(nwbfile, pynwb.NWBFile), "'nwbfile' should be of type pynwb.NWBFile"
    170     if isinstance(recording, RecordingExtractor):
--> 171         checked_recording = OldToNewRecording(oldapi_recording_extractor=recording)
    172     else:
    173         checked_recording = recording

~/miniconda3/envs/buzsaki-lab-to-nwb-env/lib/python3.7/site-packages/spikeinterface/core/old_api_utils.py in __init__(self, oldapi_recording_extractor)
    191         if gains is not None:
    192             if np.any(gains != 1):
--> 193                 self.set_channel_gains(gains)
    194         if offsets is not None:
    195             if np.any(offsets != 0):

~/miniconda3/envs/buzsaki-lab-to-nwb-env/lib/python3.7/site-packages/spikeinterface/core/baserecording.py in set_channel_gains(self, gains, channel_ids)
    493         if np.isscalar(gains):
    494             gains = [gains] * self.get_num_channels()
--> 495         self.set_property('gain_to_uV', gains, ids=channel_ids)
    496 
    497     def get_channel_gains(self, channel_ids=None):

~/miniconda3/envs/buzsaki-lab-to-nwb-env/lib/python3.7/site-packages/spikeinterface/core/base.py in set_property(self, key, values, ids)
    150         values = np.asarray(values)
    151         if ids is None:
--> 152             assert values.shape[0] == size
    153             self._properties[key] = values
    154         else:

AssertionError: 
```

## Steps to Reproduce
TBD

## Environment
Running the latest versions of `nwb-conversion-tools` and `spikeinterface`

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by alejoe91** [comment]
@h-mayorquin good point. This is a tricky one, because it would require an even higher complexity in parsing the nested dictionary in `spikeinterface`. The best solution in my opinion is to convert to a new object at the beginning of the function and to use the new API to slice channels:
```
def subset_shank_channels(recording_extractor: Union[se.RecordingExtractor, si.BaseRecording], xml_file_path: str) -> si.BaseRecording: 
     """Attempt to create a SubRecordingExtractor containing only channels related to neural data.""" 
     if isinstance(recording_extractor, se.RecordingExtractor):
          recording = si.OldToNewRecording(recording_extractor)
     else:
          recording = recording_extractor
     shank_channels = get_shank_channels(xml_file_path=xml_file_path) 
     if shank_channels is not None: 
         channel_ids = [channel_id for group in shank_channels for channel_id in group]
         sub_recording = recording.channel_slice(channel_ids)
     else: 
         sub_recording = recording 
     return sub_recording 
```

Can you check if this works on your side?
