### ISSUE TITLE
v0.11 util vs. tool nesting

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/nwb-conversion-tools#400]
It's been requested for a long time by @bendichter to use a more proper `utils` designation applying only to functions that contain no external dependencies beyond the standard python library. Anything that depends on stuff like `pynwb` or `spikeinterface` should really, then, be classified as a `tools` function instead. Below are some proposals for how this ought to be nested, and I wanted to get everyone's feedback on which looks nicest.

@alejoe91 has also requested that commonly used tool functions for SI be exposed at a higher level (ideally `from nwb_conversion_tools import write_recording`), and while implementing this is as easy as updating the `__init__.py` for the package independent of the `utils`/`tools` discrepancy, I have some ambiguity concerns with respect to the naming schemes there, which I highlight at the end of each proposal.

(a)

```
nwb_conversion_tools
  - data_interfaces
    -- All the various interfaces we use
  - schemas
    -- All the various JSON schemas we use
  - utils
    -- schemas
      --- Basically, all the internal schematic retrieval utilities we use like get_schema_from_hdmf_class
    -- dict
      --- Dictionary-specific utils, of which we have several but the most important being dict_deep_update
  - write_tools
    -- nwbfile.py
    -- yaml_conversion_specification.py
    -- spikeinterface
      --- write functions as well as generic iterator
    -- roiextractors
      --- write functions as well as generic iterator (TODO)
    -- neo
      --- the ABF reader and other future icephys stuff
```

@alejoe91 - For unexposed imports, this would look like `from nwb_conversion_tools.write_tools.spikeinterface import write_recording`. My concern here is that, when exposed at the highest level, `from nwb_conversion_tools import write_recording` doesn't indicate any specificity to SpikeInterface; so when we eventually add neo support or anything similar, it could be ambiguous what kind of 'recording' we are writing; whereas when unexposed, the way it is imported clearly indicates the type of recording being references. Re-naming the function to `write_spike_interface_recording` could otherwise resolve this ambiguity, but then a direct unexposed import of `from nwb_conversion_tools.write_tools.spikeinterface import write_spike_interface_recording` seems excessively verbose.

(b)

```
nwb_conversion_tools
  - data_interfaces
    -- ecephys
      --- baserecordinginterface.py, ...
      --- write_tools
        ---- SpikeInterface write functions as well as generic iterator. The idea here is that these tools
        ---- are so specific to these interfaces, they could live next to each other.
    -- ophys
      --- baseimaginginterface.py, ...
      --- write_tools
        ---- roiextractor write functions as well as generic iterator. The idea here is that these tools
        ---- are so specific to these interfaces, they could live next to each other.
    -- icephys
      --- baseicephysinterface.py
      --- write_tools
        ---- the ABF reader and other future icephys/neo stuff. The idea here is that these tools
        ---- are so specific to these interfaces, they could live next to each other.
  - schemas
    -- All the various JSON schemas we use
  - utils
    -- schemas
      --- Basically, all the internal schematic retrieval utilities we use like get_schema_from_hdmf_class
    -- dict
      --- Dictionary-specific utils, of which we have several but the most important being dict_deep_update
  - tools
    -- nwbfile.py
    -- yaml_conversion_specification.py
```

@alejoe91 - unexposed:  `from nwb_conversion_tools.data_interfaces.ecephys.write_tools.spikeinterface import write_recording` I'll admit, that is so utterly nested it just needs to be exposed regardless. In this case I'd just insert `_spike_interface_` into all the function names to make it obvious that's the type of recording being referred to.

(c)

```
nwb_conversion_tools
  - data_interfaces
    -- All the various interfaces we use
  - schemas
    -- All the various JSON schemas we use
  - utils
    -- schemas
      --- Basically, all the internal schematic retrieval utilities we use like get_schema_from_hdmf_class
    -- dict
      --- Dictionary-specific utils, of which we have several but the most important being dict_deep_update
  - tools
    -- nwbfile.py
    -- yaml_conversion_specification.py
    -- writing
      --- spikeinterface
        ---- write functions as well as generic iterator
      --- roiextractors
        ---- write functions as well as generic iterator (TODO)
      --- neo
        ---- the ABF reader and other future icephys stuff
```

@alejoe91 - similar to (b), nesting becomes undeniably complicated.

Open to all other suggestions as well; trying to make the structure and clean, organized, and intuitive as possible.

**Comment by alejoe91** [comment]
I agree with the name changing (maybe keep a Deprecation warning for a while) and going for option (a). What about `write_si_recording`/`write_si_sorting`? or `write_spikeinterface_recording()` (without the extra _)

**Comment by CodyCBakerPhD** [comment]
Suggestion from meeting `nwb_conversion_tools.spikeinterface import write_recording` alias of `nwb_conversion_tools.tools.spikeinterface import write_recording`

**Comment by CodyCBakerPhD** [comment]
Also `tools` instead of `write_tools`
