### ISSUE TITLE
Write SpikeExtractor for Bonsai

### ISSUE THREAD

**Issue by nicolocin** [catalystneuro/nwb-conversion-tools#41]
Once catalystneuro/neuroconv#10 is sorted, write BonsaiSpikeExtractor using template provided [here](https://spikeinterface.readthedocs.io/en/latest/sorting_extractor.html).  Sample extractors for other formats can be found [here](https://github.com/SpikeInterface/spikeextractors/tree/master/spikeextractors/extractors)

@bendichter @glopesdev

**Comment by h-mayorquin** [comment]
I guess this has been superseded by:
https://github.com/catalystneuro/neuroconv/issues/47
