### ISSUE TITLE
pip install failing due to herding spikes

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/nwb-conversion-tools#410]
## Description

While discussing some pip issues in #408 I tried to do a clean pip install of `nwb-conversion-tools` and it failed with the following error:

```python
ERROR: Cannot install nwbn-conversion-tools==0.1.1, nwbn-conversion-tools==0.2.0, nwbn-conversion-tools==0.3.0, nwbn-conversion-tools==0.3.2 and nwbn-conversion-tools==0.3.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    nwbn-conversion-tools 0.3.3 depends on herdingspikes
    nwbn-conversion-tools 0.3.2 depends on herdingspikes
    nwbn-conversion-tools 0.3.0 depends on herdingspikes
    nwbn-conversion-tools 0.2.0 depends on herdingspikes
    nwbn-conversion-tools 0.1.1 depends on herdingspikes

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

It seems that the problem is created by `herdingspikes` not finding `numpy`.  See line 36 in the full error trace which is contained in the following link: 

https://gist.github.com/h-mayorquin/0a443d5b94c4a342e1fe1291c8b24efa

## Steps to Reproduce

In a terminal:
```bash
conda create --name test python=3.7
conda activate test
pip install nwbn-conversion-tools
```

## Environment
    Python Executable: Conda 
    Python Version: Python 3.7
    Operating System: Ubuntu Linux 
   
## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by CodyCBakerPhD** [comment]
> conda create --name test python=3.7
conda activate test
pip install nwbn-conversion-tools

`pip install nwbn-conversion-tools` != `pip install nwb-conversion-tools` 😉

**Comment by h-mayorquin** [comment]
I saw the spelling and I thought it was like that for a reason:
So we do have two packages:
https://pypi.org/project/nwb-conversion-tools/
And
https://pypi.org/project/nwbn-conversion-tools/

Shouldn't we get rid of it?
It seems to be owned by @bendichter  and @luiztauffer

**Comment by bendichter** [comment]
yes, lets get rid of it. I can do it

**Comment by CodyCBakerPhD** [comment]
@bendichter Thanks! That actually really helps resolve that old annoying ambiguity
