### ISSUE TITLE
[Bug]: `check_recordings_equal` from `spikeinterface` fails when using non integer channel ids. 

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/nwb-conversion-tools#429]
@bendichter @alejoe91 @samuelgarcia @CodyCBakerPhD 

## Problem and context
Hi, I wanted to discuss the following issue. We recently added capabilities for `spikeinterface` to handle non integer channels #415. During the discussion of that aforementioned PR the following difficulty ensued. Many of our round trip tests use `NwbRecordingExtractor` for testing that we indeed wrote the nwb file correctly. Here is an example:

https://github.com/catalystneuro/nwb-conversion-tools/blob/712c775a4660171fd8c1467eaf28e6d604538183/tests/test_internals/test_si.py#L289-L297

The problem with this approach is that, as it stands, the **`NwbRecordingExtractor` assumes that the `channel_ids` are equivalent to the `electrode.table.ids` and thus it fails for recordings with non integer channels** (see example in steps to reproduce below).

## Possible solutions
Some possible solutions that come to my mind are:
Within `spikeinterface`
1) Remove the assumption that channels ids are equivalent to the electrode ids altogether in the `NwbRecordingExtractor`.  
2) In `check_recordings_equal` if the channel_ids of any of the electrodes is of type other than integer, then skip the comparison of channel_ids. 

Within `nwb-conversion-tools` 
1) Remap the ids of `NwbRecordingExtractor` channel_ids to the field `channel_name` (as we implemented it) before we do a full recorder comparison with `check_recordings_equal`
2) Wrap the `NwbRecordingExtractor` so we change the assignation of ids from the `electrodes.table.id` to `electrodes.table.channel_name` as we already have the functionality to write it like this.

### Steps to Reproduce

```python
from nwb_conversion_tools.tools.spikeinterface import spikeinterface
from spikeinterface.core.testing_tools import generate_recording
from spikeinterface.core.testing import check_recordings_equal
from spikeinterface.extractors import NwbRecordingExtractor

from nwb_conversion_tools.tools.spikeinterface import get_nwb_metadata
from datetime import datetime

rec = generate_recording(num_channels=4, durations=[10])
channel_ids = rec.get_channel_ids()
non_int_channel_ids = ['a', 'b', 'c', 'd']
rec_non_int_channels = rec.channel_slice(channel_ids=channel_ids, renamed_channel_ids=non_int_channel_ids)

metadata = get_nwb_metadata(recording = rec_non_int_channels)
metadata["NWBFile"]["session_start_time"] = datetime.now()
# make_nwbfile_from_metadata()

nwbfile = spikeinterface.write_recording(recording=rec_non_int_channels, save_path="temp.nwb", metadata=metadata)

nwb_recorder = NwbRecordingExtractor(file_path="temp.nwb")
check_recordings_equal(nwb_recorder, rec_non_int_channels)
```

### Traceback

```python
/home/heberto/development/nwb-conversion-tools/nwb_conversion_tools/utils/dict.py:174: UserWarning: input to update should be a dict, returning output
  warnings.warn("input to update should be a dict, returning output")
/home/heberto/miniconda3/envs/nwb_conversion_testing_env/lib/python3.9/site-packages/pynwb/file.py:1037: UserWarning: Date is missing timezone information. Updating to local timezone.
  warn("Date is missing timezone information. Updating to local timezone.")
Traceback (most recent call last):
  File "/home/heberto/development/nwb-conversion-tools/development_file.py", line 22, in <module>
    check_recordings_equal(nwb_recorder, rec_non_int_channels)
  File "/home/heberto/miniconda3/envs/nwb_conversion_testing_env/lib/python3.9/site-packages/spikeinterface/core/testing.py", line 10, in check_recordings_equal
    assert np.allclose(RX1.get_channel_ids(), RX2.get_channel_ids())
```
### Operating System

Linux

### Python Executable

Python

### Python Version

3.9

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

**Comment by alejoe91** [comment]
@h-mayorquin I think we need to update the `NwbRecordingExtractor` accordingly, i.e., loading the `channel_name` column when present as channel ids. Note that the non-string problem can also happen in unit id, so we should also add a `unit_name` column in the Units table and make the same changed in the `NwbSortingExtractor`.

Do you want to give it a try and make a PR to SpikeInterface?

**Comment by h-mayorquin** [comment]
Yes. I can take a stab at that. I also happen to think that it is the cleaner solution.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin @alejoe91 Is this issue resolved with #[550](https://github.com/SpikeInterface/spikeinterface/pull/550)?

**Comment by h-mayorquin** [comment]
Yes.
Altought there is still issue discussed above of adding a property `unit_name` to the units table and do the corresponding changes in the `spikeinterface` functions but I guess we can open a different issue for that.

**Comment by h-mayorquin** [comment]
> @h-mayorquin Right, those are planned refactors of the `write_sorting` and `NwbSortingExtractor` similar to what you did for the `ElectrodesTable`?

Right, correct. Mostly `add_units` rather than `write_sorting` I think. 
So we can close this.
