### ISSUE TITLE
[Feature]: neuralynx session_start_time

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#437]
### What would you like to see added to nwb-conversion-tools?

pull session_start_time from neuralynx file header

### What solution would you like?

pull session_start_time from neuralynx file header

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

**Comment by CodyCBakerPhD** [comment]
Neuralynx has a lot of versions: https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/neuralynx

Do all of them support this, and is access to the header easy via neo or SI helpers?
