### ISSUE TITLE
[Documentation]: Provide example conversion code in the docstring of each non-abstract DataInterface

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#442]
### What would you like changed or added to the documentation and why?

Provide example conversion code in the docstring of each non-abstract DataInterface

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

**Comment by h-mayorquin** [comment]
At this point what we are missing are the segmentation extractors. For this, if we want to have the same structure I am blocked by the last part of issue #511: the `run_conversion` function for the segmentation interfaces has not been unified to have the same signature. Once that is done, we can add the rest of the ophys interfaces with a common format across all the library.

Finally, when #552 is addressed this issue can be closed.

**Comment by h-mayorquin** [comment]
@bendichter so this ended up being converted to the conversion gallery. Can we close this or is there something else to do?
