### ISSUE TITLE
[Feature]: stream_id argument not propagating down into write_electrical_series

### ISSUE THREAD

**Issue by Saksham20** [catalystneuro/nwb-conversion-tools#443]
### What would you like to see added to nwb-conversion-tools?

With the new spike interface, recording extractors support multiple streams: each stream will have its own signal traces which  the user may want to write in a separate `ElectricalSeries` container. 

We are not propagating `segment_index` argument in `write_recording` [here](https://github.com/catalystneuro/nwb-conversion-tools/blob/f2ceb69e744ef800d907ebb09668e09037b1ee24/nwb_conversion_tools/tools/spikeinterface/spikeinterface.py#L848) which is used by add_electrical_series [here](https://github.com/catalystneuro/nwb-conversion-tools/blob/f2ceb69e744ef800d907ebb09668e09037b1ee24/nwb_conversion_tools/tools/spikeinterface/spikeinterface.py#L454). A user may want to add multiple segments info into one nwbfile. Subsequently, the `segment_index` must also be a default arg for the `run_conversion()` for the user to control. 

For example, In case of spikeglx files this segment index corresponds to g0_t0/g1_t1 ... and there could be multiple segments for each stream_id specified.

### What solution would you like?

adding default arg: `run_conversion(segment_index=0, ...)` and `write_recording(segment_index=0,...)`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

**Comment by h-mayorquin** [comment]
There are two issues here: stream propagation and multi segment support.
**stream propagation**
The spikeinterface recorders that I have seen do not allow the user to initialize the recorder in the presence of multiple segment. A choice has to be make at the __init__ of the interfaces about which stream to propagate. Two examples where this choice can be seen in action:
1) See for example the super in the init of the PR #573 where the stream was chosen to keep backwards compatiblity.
2)  For spikeglx we propagate one of the streams as the "raw" data and another as the "lfp" and we process them through different interfaces.

What I want to emphasize with these two examples is that I don't think there is a unified choice that can be propagate all the way down to the electrical series. The choice of which part of the extractor to propagate is probably best made at the init of the data interface in a case per case basis.

**multi segment support**
This is a different issue, see #579

**Comment by h-mayorquin** [comment]
I am going to close this issue as I think one of the main points has been answered and the second now has an issue on its own.
