### ISSUE TITLE
[Feature]: add kilosort

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#451]
### What would you like to see added to nwb-conversion-tools?

https://github.com/SpikeInterface/spikeinterface/blob/134c1b8d8d3177b6dba701d64d9e52a07053f633/spikeinterface/extractors/phykilosortextractors.py#L173

### What solution would you like?

add kilosort

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

**Comment by CodyCBakerPhD** [comment]
It looks as though that extractor is simply a wrapper around the PhyExtractor that enforces different default values; if we added the `keep_good_only` argument to our [PhyDataInterface](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/nwb_conversion_tools/datainterfaces/ecephys/phy/phydatainterface.py) (and added the SI backend to it as well) then that should be all we need for this
