### ISSUE TITLE
pip installation

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/nwb-conversion-tools#46]
Upon first installation, calling `pip install nwb-conversion-tools` without a cloned repository is unable to find the package. Is this posted to PyPI yet?

**Comment by luiztauffer** [comment]
this is because the package name on pypi is still `nwbn-conversion-tools`, we dropped the n recently. I can create a new project on pypi with the proper name. 
Now, should we stop updating the `nwbn-` project right away, leaving it only as legacy? @bendichter

**Comment by bendichter** [comment]
Yes please do that

**Comment by luiztauffer** [comment]
@CodyCBakerPhD @bendichter 
there were a lot of changes since I last contributed to the repo, so I'm not 100% up to date with everything. For now, we have it published on test Pypi and I think it would be wise to test it before we publish on the official pypi. You can do this:

```
pip install -i https://test.pypi.org/simple/ nwb-conversion-tools
```

**Comment by bendichter** [comment]
@luiztauffer test pypi is usually used for testing deployment, not testing of the package itself. If there are problems, we can always cut a new release. Is there a problem with that?

**Comment by luiztauffer** [comment]
so, what do you guys think, should we put out the current version already?
@bendichter @CodyCBakerPhD

**Comment by bendichter** [comment]
Yeah go for it!

**Comment by CodyCBakerPhD** [comment]
It has been pretty stable since v0.6.0... might need to update/expand the examples in the to-nwb-template repo for demonstration however, I'll check
