### ISSUE TITLE
`test_dandi_upload` should take into account if environment variable is present or not

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/nwb-conversion-tools#497]
The following test is failing in my system because i don't have the dandi key set:
https://github.com/catalystneuro/nwb-conversion-tools/blob/d2650eef7fce8b6973b8a48f5ec0df0239d8033e/src/nwb_conversion_tools/tools/data_transfers.py#L181-L184

Test should not fail in expected behavior. I think that:
1) The test should be skipped if the environment variable is not present, or/and
2) The machinery described in the following should be actually tested:
https://github.com/catalystneuro/nwb-conversion-tools/blob/d2650eef7fce8b6973b8a48f5ec0df0239d8033e/src/nwb_conversion_tools/tools/data_transfers.py#L181-L184

**Comment by CodyCBakerPhD** [comment]
> The test should be skipped if the environment variable is not present

Sure, that's fine

**Comment by CodyCBakerPhD** [comment]
Test isn't failing on the CI due to that though, something is going on with the dandi schema versions

**Comment by h-mayorquin** [comment]
> Test isn't failing on the CI due to that though, something is going on with the dandi schema versions

I did not see the issue until I finished writing this.
