### ISSUE TITLE
Bug in the movie data interface only appearing on CI

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/nwb-conversion-tools#499]
The following pull requested introduced a hard-to-pin bug in the tests for the move interface whose behavior is rather randomly:
https://github.com/catalystneuro/nwb-conversion-tools/pull/468

The bug does not fail consistently: It has not failed in my local machine for example and it does not fail all the time but it fails in the CI sometimes and usually re-running the test in the CI solves it. That said, I think is bad that we have this bug out there and priorities allowing, I will allocate some time next week to try to track it down.

Here we have an instance of the error appearing on [Minimal and full tests on windows-latest with Python 3.8](https://github.com/catalystneuro/nwb-conversion-tools/runs/6303450593?check_suite_focus=true#logs)

I saved a [gist](https://gist.github.com/h-mayorquin/86cbce7d321115bc235a2b0cfffebacf) with the error trace in case that link is not stable.

**Comment by CodyCBakerPhD** [comment]
Feels like we haven't seen this in a while, good to close?

**Comment by h-mayorquin** [comment]
Yes, no point in leaving this hanging. We re-open if it comes back. Hopefully it won't.
