### ISSUE TITLE
[Feature]: read metadata for intan

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#507]
### What would you like to see added to nwb-conversion-tools?

We can pull electrode-specific information from the header.

### What solution would you like?

See @alejoe91's pyintan code [here](https://github.com/alejoe91/pyintan/blob/master/pyintan/intan.py).

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

**Comment by h-mayorquin** [comment]
Right now we are extracting some electrode information (such as group names) using the readers provide with that library:

https://github.com/catalystneuro/nwb-conversion-tools/blob/8959b11591494418bf0e32be779e935a3415f54a/src/nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py#L11-L30

(See also #561)

Is the idea to drop the dependency on `pyintan`?

In `spikeinterface` the same information we are extracting through `pyintan` is automatically fetched from the neo headers:
https://github.com/catalystneuro/nwb-conversion-tools/pull/561/files

**Comment by bendichter** [comment]
Yes, please use the headers as parsed by neo.

**Comment by h-mayorquin** [comment]
> We'd still need `pyintan` when using `spikeextractors_backend=True` I assume.

Yes, and right now I am using it to temporarily extract the time even in the case when `spikeextractors_backend=False` 

> Also, does the SpikeInterface/neo passed metadata necessarily contain everything that `pyintan` would grab?
> 
> In general this issue was raised because Intan header files contain a large amount of information, not just channel name stuff but also things like impedence that could get added to those optional fields of the ElectrodesTable

Once I am done with #500 I will start looking at #501 systematically and check for this. My shallow reading of the code yesterday indicates that the code in neo is similar to Alessio's code in `pyintan` but I will check it in detail when the time comes.

**Comment by CodyCBakerPhD** [comment]
> My shallow reading of the code yesterday indicates that the code in neo is similar to Alessio's code in pyintan but I will check it in detail when the time comes.

Oh right, I remember seeing that, it seemed like they basically copied/pasted the base code from `pyintan` to `neo` instead.

**Comment by CodyCBakerPhD** [comment]
Mostly added in #561, would need to deep dive into modern-day neo annotations to see if there's anything else to include but that goes for a lot of other interfaces too, so deferring to https://github.com/catalystneuro/neuroconv/issues/43
