### ISSUE TITLE
[Feature]: create RoiextractorsDataChunkIterator

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/nwb-conversion-tools#518]
### What would you like to see added to nwb-conversion-tools?

The roiextractirs write methods uses the old DataChunkIterator class - I would like this updated to use the new GenericDataChunkIterator.

### What solution would you like?

MovieDataChunkIterator

Would also like to buffer over multiple frames and have efficient cross-frame chunking for smaller image sizes

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

**Comment by weiglszonja** [comment]
Closing this as it was merged in https://github.com/catalystneuro/neuroconv/pull/54
