### ISSUE TITLE
Running spike sorting inside nwb-conversion-tools?

### ISSUE THREAD

**Issue by alejoe91** [catalystneuro/nwb-conversion-tools#55]
In the `ecephys` module there is a `run_spike_sorting` function: https://github.com/catalystneuro/nwb-conversion-tools/blob/90d4a560fd08236081531c0b6a81067f4a066b05/nwb_conversion_tools/ecephys/ecephys.py#L90

Do you think it belongs to this repo? I think that this package should focus on conversion and allowing users to easily extend on its classes/functions to package their data into an NWB file. 

The same goes for the `most_relevant_ch` function (I can add something like that in the preprocessing module of spiketoolkit).

Maybe analysis tools should be kept as a separate package/resource.

**Comment by bendichter** [comment]
Yes, I think it is better to leave those functions to SpikeInterface

**Comment by CodyCBakerPhD** [comment]
@alejoe91 Agreed, spike sorting is a far more nuanced and detailed process that requires user control. Our scope here is simply to take common data formats that have been processed and output them directly, and easily, into NWB format.
