### ISSUE TITLE
`get_metadata_schema` in BaseImagingExtractorInterface needs a small refactor

### ISSUE THREAD

**Issue by weiglszonja** [catalystneuro/nwb-conversion-tools#556]
Accessing the private attribute sampling frequency and casting to float in `get_metadata_schema` is not a proper place to have anymore, I think it should be removed.
https://github.com/catalystneuro/nwb-conversion-tools/blob/07e958d7564eb12d00a5ff5fabe661677d023efa/src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py#L27-L29

@CodyCBakerPhD what do you think?

**Comment by weiglszonja** [comment]
@CodyCBakerPhD How would you do it? I was thinking to add a decorator (yeah, I know...) that checks the return value of the `get_sampling_frequency` function:

```python
def check_get_sampling_frequency_return_dtype(func):
    """ A decorator to check the return value of a function is of float type. """

    @wraps(func)
    def wrapper(*args, **kwargs):
        return_value = func(*args, **kwargs)
        if not isinstance(return_value, float):
            return_value = float(return_value)
        return return_value

    return wrapper
```

**Comment by bendichter** [comment]
We are already using typehints:

https://github.com/catalystneuro/roiextractors/blob/2361597b8234e988e6d70e661b7b20428ff32c99/src/roiextractors/imagingextractor.py#L38-L40

**Comment by CodyCBakerPhD** [comment]
> @CodyCBakerPhD How would you do it? I was thinking to add a decorator (yeah, I know...) 

I would simply write a test on the ROIExtractors side to ensure the output of each extractor `.get_sampling_frequency` is a float type.

The conversion tools shouldn't do too much magic like this on their own, they should ideally just expect particular forms of inptus/outputs and not behavior correctly if that is violated.

I did look into Pydantic type stuff for this a while back but the huge downside to that is they are not compatible with numpy data typing, and complicated unions of things can throw it off.

**Comment by bendichter** [comment]
yes, well put, Cody. Magic like this is difficult to maintain and tests are much simpler and just as effective.

**Comment by h-mayorquin** [comment]
The only place in the pipeline where we need this was changed recently and now does a casting over there:
https://github.com/catalystneuro/nwb-conversion-tools/blob/07e958d7564eb12d00a5ff5fabe661677d023efa/src/nwb_conversion_tools/tools/roiextractors/roiextractors.py#L110

I just tested removing this and it works as it is.

**Comment by h-mayorquin** [comment]
Concerning checking for sampling rate equal being a float in imaging extractor, check:
https://github.com/catalystneuro/roiextractors/pull/164

**Comment by h-mayorquin** [comment]
This is removed now in #559. 
Should we close the issue @weiglszonja ?

**Comment by weiglszonja** [comment]
Yeah its fine, I’ll close it.
