### ISSUE TITLE
using lxml instead of BeautifulSoup

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#58]
@CodyCBakerPhD do you mind looking into using lxml for XML parsing instead of bs4?

**Comment by CodyCBakerPhD** [comment]
Sure thing; is this just for nwb-conversion-tools or also for SpikeInterface?

**Comment by bendichter** [comment]
also SpikeInterface

**Comment by CodyCBakerPhD** [comment]
Should be all done now; I don't think there was any usage of it here in nwb-conversion-tools as it's a Buzsaki/Neuroscope specific thing so that actual commits are in those respective repositories.

**Comment by bendichter** [comment]
Thanks. In the future could you make that a separate PR? Try to make your PRs modular if you can.

**Comment by CodyCBakerPhD** [comment]
Ah, good point. Will do!

**Comment by CodyCBakerPhD** [comment]
I do believe all references to `soup` in `buzsaki-labl-to-nwb`, `SpikeInterface`, and `to_nwb.neuroscope`, have all been replaced by `lxml`. Are there any other repositories you can think of that include `soup` or does that close this issue?
