### ISSUE TITLE
linking to Devices

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#60]
We want a form that allows objects to be linked to other objects, and for the user to select this relationships. For instance, for an `ImagingPlane`, a user must select which `Device` from available devices it should link. This situation is not handled well by JSON-schema. See conversation about this [here](https://github.com/json-schema-org/json-schema-spec/issues/331). There was a proposal to include a $data keyword arg, so in the schema the relationship would be handled as something like 

```json
"ImagingPlanes": {
          "type": "array",
          "items": {
            "title": "ImagingPlane",
            "type": "object",
            "required": ["name", "description"],
            "properties": {
              "name": {"type": "string", "default": "ImagingPlane"},
              "description": {"type": "string", "description": "An area in the brain where imaging was done"},
              "device": {"type": "string", "link": "$data/path/to/devices/*/name"},
              ...
                    }
                }
              }
            }
```

JSON-schema does not want to add this to core because it would require all implementations to implement this, but I think it should work for us

**Comment by oruebel** [comment]
You could use YAML instead, which allows referencing of data objects via Anchors (&) and Aliases (*)

**Comment by bendichter** [comment]
Interesting, that might be useful. We specifically need a schema language that allows us to do this though. Would this be possible in a yaml schema language?

**Comment by oruebel** [comment]
I believe so, but I'm not 100% sure

**Comment by luiztauffer** [comment]
for now we are using a `target` key on properties that should be a link to another object, e.g.:

```
"PlaneSegmentation": {
      "tag": "pynwb.ophys.ImageSegmentation",
      "title": "PlaneSegmentation",
      "type": "object",
      "required": ["name", "description", "imaging_plane"],
      "properties": {
        "name": {
          "type": "string",
          "description": "name of PlaneSegmentation"
        },
        "description": {
          "type": "string",
          "default": "Description of image plane, recording wavelength, depth, etc."
        },
        "imaging_plane": {
          "type": "string",
          "description": "the ImagingPlane this ROI applies to",
          "target": "pynwb.ophys.ImagingPlane"
        }
      }
    },
```
