### ISSUE TITLE
Remove all GUI-related stuff

### ISSUE THREAD

**Issue by alejoe91** [catalystneuro/nwb-conversion-tools#65]
With [NWB-web-GUI](https://github.com/catalystneuro/nwb-web-gui) we should remove all the GUI related files and dependencies from nwb-conversion-tools, so that we make it as light-weight as possible.

Should I start this in a new branch @bendichter @luiztauffer @CodyCBakerPhD ?

**Comment by bendichter** [comment]
Yes we will eventually do this but let's hold off until the new gui is ready

**Comment by luiztauffer** [comment]
to leave here as a reference, the Qt gui can be found here: https://github.com/catalystneuro/nwb-qt-gui
It will probably fail to run conversion properly, given the major changes in the conversion tools.
