### ISSUE TITLE
fill_defaults() usage

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-conversion-tools#95]
What is the function `fill_defaults()` supposed to do exactly?

https://github.com/catalystneuro/nwb-conversion-tools/blob/7395586369c2ef94e8abc72b4a62db59be02ae1b/nwb_conversion_tools/basedatainterface.py#L22-L23

The line above will return None and break a Converter using a vanilla DataInterface: 

https://github.com/catalystneuro/nwb-conversion-tools/blob/7395586369c2ef94e8abc72b4a62db59be02ae1b/nwb_conversion_tools/nwbconverter.py#L73-L75

To me it does not sound right to use specific metadata values as `default` for a schema. Default schema values, if existing, should be taken from `get_schema_from_hdmf_class()`. Filling metadata data should be taken from `get_metadata()` methods and be stored in a metadata dictionary/file (which is not a schema).

@bendichter you pushed this change, right?

**Comment by bendichter** [comment]
`fill_defaults(a, b)` fills the default values of schema `a` with values from `b`. It works in-place, so there's a slight mistake I made here in that it should updated and then return on the next line. 

I thought it would be convenient to make the result of `get_metadata` be included as default values in the `metadata_schema`. Then we could have interfaces like the web gui make a single call to `get_metadata_schema`, and the result would include the values. I suppose it's not a problem to make that a separate step
